#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grV24", "comp_pPb_v24.pdf", "v_{2}{4} pPb", "v_{2}{4} Pbp", "v_{2}{4} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grV26", "comp_pPb_v26.pdf", "v_{2}{6} pPb", "v_{2}{6} Pbp", "v_{2}{6} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grV28", "comp_pPb_v28.pdf", "v_{2}{8} pPb", "v_{2}{8} Pbp", "v_{2}{8} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grC24", "comp_pPb_C24.pdf", "c_{2}{4} pPb", "c_{2}{4} Pbp", "c_{2}{4} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grV2n", "comp_pPb_v2n.pdf", "v_{2}{4} pPb 3-sub", "v_{2}{4} Pbp 3-sub", "v_{2}{4} pPb+Pbp 3-sub")'
#root -l -b -q 'compare3.C("grV2_pPb.root", "grV2_Pbp.root", "grV2_merged.root", "grC2n", "comp_pPb_C2n.pdf", "c_{2}{4} pPb 3-sub", "c_{2}{4} Pbp 3-sub", "c_{2}{4} pPb+Pbp 3-sub")'
#
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grV34", "comp_pPb_v34.pdf", "v_{3}{4} pPb", "v_{3}{4} Pbp", "v_{3}{4} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grV36", "comp_pPb_v36.pdf", "v_{3}{6} pPb", "v_{3}{6} Pbp", "v_{3}{6} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grV38", "comp_pPb_v38.pdf", "v_{3}{8} pPb", "v_{3}{8} Pbp", "v_{3}{8} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grC34", "comp_pPb_C34.pdf", "c_{3}{4} pPb", "c_{3}{4} Pbp", "c_{3}{4} pPb+Pbp")'
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grV3n", "comp_pPb_v3n.pdf", "v_{3}{4} pPb 3-sub", "v_{3}{4} Pbp 3-sub", "v_{3}{4} pPb+Pbp 3-sub")'
#root -l -b -q 'compare3.C("grV3_pPb.root", "grV3_Pbp.root", "grV3_merged.root", "grC3n", "comp_pPb_C3n.pdf", "c_{3}{4} pPb 3-sub", "c_{3}{4} Pbp 3-sub", "c_{3}{4} pPb+Pbp 3-sub")'
#
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grV24", "comp_pPb_track_v24.pdf", "v_{2}{4} Tight", "v_{2}{4} Loose", "v_{2}{4} standard")'
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grV26", "comp_pPb_track_v26.pdf", "v_{2}{6} Tight", "v_{2}{6} Loose", "v_{2}{6} standard")'
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grV28", "comp_pPb_track_v28.pdf", "v_{2}{8} Tight", "v_{2}{8} Loose", "v_{2}{8} standard")'
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grC24", "comp_pPb_track_c24.pdf", "c_{2}{4} Tight", "c_{2}{4} Loose", "c_{2}{4} standard")'
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grV2n", "comp_pPb_track_v2n.pdf", "v_{2}{4} Tight 3-sub", "v_{2}{4} Loose 3-sub", "v_{2}{4} standard 3-sub")'
#root -l -b -q 'compare3.C("grV2_sysTight.root", "grV2_sysLoose.root", "grV2_merged.root", "grC2n", "comp_pPb_track_c2n.pdf", "c_{2}{4} Tight 3-sub", "c_{2}{4} Loose 3-sub", "c_{2}{4} standard 3-sub")'
#
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grV34", "comp_pPb_track_v34.pdf", "v_{3}{4} Tight", "v_{3}{4} Loose", "v_{3}{4} standard")'
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grV36", "comp_pPb_track_v36.pdf", "v_{3}{6} Tight", "v_{3}{6} Loose", "v_{3}{6} standard")'
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grV38", "comp_pPb_track_v38.pdf", "v_{3}{8} Tight", "v_{3}{8} Loose", "v_{3}{8} standard")'
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grC34", "comp_pPb_track_c34.pdf", "c_{3}{4} Tight", "c_{3}{4} Loose", "c_{3}{4} standard")'
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grV3n", "comp_pPb_track_v3n.pdf", "v_{3}{4} Tight 3-sub", "v_{3}{4} Loose 3-sub", "v_{3}{4} standard 3-sub")'
#root -l -b -q 'compare3.C("grV3_sysTight.root", "grV3_sysLoose.root", "grV3_merged.root", "grC3n", "comp_pPb_track_c3n.pdf", "c_{3}{4} Tight 3-sub", "c_{3}{4} Loose 3-sub", "c_{3}{4} standard 3-sub")'

#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grV24", "comp_pPb_vz_v24.pdf", "v_{2}{4} |vz|<3.0", "v_{2}{4} 3.0<|vz|<15.", "v_{2}{4} standard")'
#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grV26", "comp_pPb_vz_v26.pdf", "v_{2}{6} |vz|<3.0", "v_{2}{6} 3.0<|vz|<15.", "v_{2}{6} standard")'
#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grV28", "comp_pPb_vz_v28.pdf", "v_{2}{8} |vz|<3.0", "v_{2}{8} 3.0<|vz|<15.", "v_{2}{8} standard")'
#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grC24", "comp_pPb_vz_c24.pdf", "c_{2}{4} |vz|<3.0", "c_{2}{4} 3.0<|vz|<15.", "c_{2}{4} standard")'
#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grV2n", "comp_pPb_vz_v2n.pdf", "v_{2}{4} |vz|<3.0 3-sub", "v_{2}{4} 3.0<|vz|<15 3-sub", "v_{2}{4} standard 3-sub")'
#root -l -b -q 'compare3.C("grV2_sysNarrow.root", "grV2_sysWide.root", "grV2_merged.root", "grC2n", "comp_pPb_vz_c2n.pdf", "c_{2}{4} |vz|<3.0 3-sub", "c_{2}{4} 3.0<|vz|<15 3-sub", "c_{2}{4} standard 3-sub")'

#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grV34", "comp_pPb_vz_v34.pdf", "v_{3}{4} |vz|<3.0", "v_{3}{4} 3.0<|vz|<15.", "v_{3}{4} standard")'
#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grV36", "comp_pPb_vz_v36.pdf", "v_{3}{6} |vz|<3.0", "v_{3}{6} 3.0<|vz|<15.", "v_{3}{6} standard")'
#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grV38", "comp_pPb_vz_v38.pdf", "v_{3}{8} |vz|<3.0", "v_{3}{8} 3.0<|vz|<15.", "v_{3}{8} standard")'
#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grC34", "comp_pPb_vz_c34.pdf", "c_{3}{4} |vz|<3.0", "c_{3}{4} 3.0<|vz|<15.", "c_{3}{4} standard")'
#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grV3n", "comp_pPb_vz_v3n.pdf", "v_{3}{4} |vz|<3.0 3-sub", "v_{3}{4} 3.0<|vz|<15 3-sub", "v_{3}{4} standard 3-sub")'
#root -l -b -q 'compare3.C("grV3_sysNarrow.root", "grV3_sysWide.root", "grV3_merged.root", "grC3n", "comp_pPb_vz_c3n.pdf", "c_{3}{4} |vz|<3.0 3-sub", "c_{3}{4} 3.0<|vz|<15 3-sub", "c_{3}{4} standard 3-sub")'


root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grV24", "comp_PbPb_track_v24.pdf", "v_{2}{4} Tight",       "v_{2}{4} Loose",       "v_{2}{4} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grV26", "comp_PbPb_track_v26.pdf", "v_{2}{6} Tight",       "v_{2}{6} Loose",       "v_{2}{6} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grV28", "comp_PbPb_track_v28.pdf", "v_{2}{8} Tight",       "v_{2}{8} Loose",       "v_{2}{8} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grC24", "comp_PbPb_track_c24.pdf", "c_{2}{4} Tight",       "c_{2}{4} Loose",       "c_{2}{4} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grV2n", "comp_PbPb_track_v2n.pdf", "v_{2}{4} Tight 3-sub", "v_{2}{4} Loose 3-sub", "v_{2}{4} standard 3-sub")'
root -l -b -q 'compare3.C("grV2PbPb_sysTight.root", "grV2PbPb_sysLoose.root", "grV2PbPb.root", "grC2n", "comp_PbPb_track_c2n.pdf", "c_{2}{4} Tight 3-sub", "c_{2}{4} Loose 3-sub", "c_{2}{4} standard 3-sub")'

root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grV34", "comp_PbPb_track_v34.pdf", "v_{3}{4} Tight",       "v_{3}{4} Loose",       "v_{3}{4} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grV36", "comp_PbPb_track_v36.pdf", "v_{3}{6} Tight",       "v_{3}{6} Loose",       "v_{3}{6} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grV38", "comp_PbPb_track_v38.pdf", "v_{3}{8} Tight",       "v_{3}{8} Loose",       "v_{3}{8} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grC34", "comp_PbPb_track_c34.pdf", "c_{3}{4} Tight",       "c_{3}{4} Loose",       "c_{3}{4} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grV3n", "comp_PbPb_track_v3n.pdf", "v_{3}{4} Tight 3-sub", "v_{3}{4} Loose 3-sub", "v_{3}{4} standard 3-sub")'
root -l -b -q 'compare3.C("grV3PbPb_sysTight.root", "grV3PbPb_sysLoose.root", "grV3PbPb.root", "grC3n", "comp_PbPb_track_c3n.pdf", "c_{3}{4} Tight 3-sub", "c_{3}{4} Loose 3-sub", "c_{3}{4} standard 3-sub")'

root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grV24", "comp_PbPb_vz_v24.pdf", "v_{2}{4} |vz|<3.0",       "v_{2}{4} 3.0<|vz|<15.",       "v_{2}{4} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grV26", "comp_PbPb_vz_v26.pdf", "v_{2}{6} |vz|<3.0",       "v_{2}{6} 3.0<|vz|<15.",       "v_{2}{6} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grV28", "comp_PbPb_vz_v28.pdf", "v_{2}{8} |vz|<3.0",       "v_{2}{8} 3.0<|vz|<15.",       "v_{2}{8} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grC24", "comp_PbPb_vz_c24.pdf", "c_{2}{4} |vz|<3.0",       "c_{2}{4} 3.0<|vz|<15.",       "c_{2}{4} standard")'
root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grV2n", "comp_PbPb_vz_v2n.pdf", "v_{2}{4} |vz|<3.0 3-sub", "v_{2}{4} 3.0<|vz|<15. 3-sub", "v_{2}{4} standard 3-sub")'
root -l -b -q 'compare3.C("grV2PbPb_sysNarrow.root", "grV2PbPb_sysWide.root", "grV2PbPb.root", "grC2n", "comp_PbPb_vz_c2n.pdf", "c_{2}{4} |vz|<3.0 3-sub", "c_{2}{4} 3.0<|vz|<15. 3-sub", "c_{2}{4} standard 3-sub")'

root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grV34", "comp_PbPb_vz_v34.pdf", "v_{3}{4} |vz|<3.0",       "v_{3}{4} 3.0<|vz|<15.",       "v_{3}{4} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grV36", "comp_PbPb_vz_v36.pdf", "v_{3}{6} |vz|<3.0",       "v_{3}{6} 3.0<|vz|<15.",       "v_{3}{6} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grV38", "comp_PbPb_vz_v38.pdf", "v_{3}{8} |vz|<3.0",       "v_{3}{8} 3.0<|vz|<15.",       "v_{3}{8} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grC34", "comp_PbPb_vz_c34.pdf", "c_{3}{4} |vz|<3.0",       "c_{3}{4} 3.0<|vz|<15.",       "c_{3}{4} standard")'
root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grV3n", "comp_PbPb_vz_v3n.pdf", "v_{3}{4} |vz|<3.0 3-sub", "v_{3}{4} 3.0<|vz|<15. 3-sub", "v_{3}{4} standard 3-sub")'
root -l -b -q 'compare3.C("grV3PbPb_sysNarrow.root", "grV3PbPb_sysWide.root", "grV3PbPb.root", "grC3n", "comp_PbPb_vz_c3n.pdf", "c_{3}{4} |vz|<3.0 3-sub", "c_{3}{4} 3.0<|vz|<15. 3-sub", "c_{3}{4} standard 3-sub")'
